### ISSUE TITLE
UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.   return _iterencode(o, 0)

### ISSUE THREAD

**Issue by sohil-hub** [jeffheaton/t81_558_deep_learning#119]
I followed the same way as mentioned in the notebook for the installation of TensorFlow in my MacBook m1.

Everything is working fine, but when I run the command "jupyter notebook" to run my notebook, my notebook keeps loading and I got this message in my terminal.

UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.   return _iterencode(o, 0)

<img width="1440" alt="Screenshot 2021-09-21 at 11 32 23 PM" src="https://user-images.githubusercontent.com/79828293/134223628-1c50484e-46f0-4597-86b6-f245a1eba566.png">

**Comment by jeffheaton** [comment]
That is just a warning, you can ignore it, mine says the same thing when starting up.  This is how mine looks:

```
(base) jeff@Jeffreys-Air ~ % jupyter notebook
[I 15:34:51.277 NotebookApp] Serving notebooks from local directory: /Users/jeff
[I 15:34:51.277 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 15:34:51.277 NotebookApp] http://localhost:8888/?token=ad8b294a1c1b663d2da00e6c2e01d568886d98f388a5c640
[I 15:34:51.277 NotebookApp]  or http://127.0.0.1:8888/?token=ad8b294a1c1b663d2da00e6c2e01d568886d98f388a5c640
[I 15:34:51.277 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:34:51.283 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jeff/Library/Jupyter/runtime/nbserver-49136-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ad8b294a1c1b663d2da00e6c2e01d568886d98f388a5c640
     or http://127.0.0.1:8888/?token=ad8b294a1c1b663d2da00e6c2e01d568886d98f388a5c640
/Users/jeff/miniforge3/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 15:38:08.604 NotebookApp] 302 GET /?token=ad8b294a1c1b663d2da00e6c2e01d568886d98f388a5c640 (::1) 0.590000ms
[I 15:38:17.185 NotebookApp] Creating new notebook in 
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x1126492e0>(<Future finis...e89"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x1126492e0>(<Future finis...e89"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/jeff/miniforge3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-12' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...6e89"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-1' coro=<MultiKernelManager._async_start_kernel() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/jupyter_client/multikernelmanager.py:186>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x107adf0d0>(<Future finis... GMT\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x107adf0d0>(<Future finis... GMT\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/jeff/miniforge3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-13' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /static...0 GMT\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/jupyter_client/manager.py:336>> is being executed.
ERROR:asyncio:Exception in callback <TaskWakeupMethWrapper object at 0x107adf310>(<Future finis...e89"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x107adf310>(<Future finis...e89"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/Users/jeff/miniforge3/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-14' coro=<HTTP1ServerConnection._server_request_loop() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /nbexte...6e89"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /Users/jeff/miniforge3/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /Users/jeff/miniforge3/lib/python3.9/site-packages/jupyter_client/manager.py:336>> is being executed.
[I 15:38:17.792 NotebookApp] Kernel started: 14ec690d-9103-4867-8c6d-197306e3bcf5, name: tensorflow
/Users/jeff/miniforge3/lib/python3.9/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
```

**Comment by sohil-hub** [comment]
Thanks a lot sir.
